### ISSUE TITLE
Code review.

### ISSUE THREAD

**Issue by kgryte** [datasets-io/cavendish-density-of-earth#1]

**Comment by Planeshifter** [comment]
For a data set this small it does not really matter, but wouldn't it be preferable to store the data set only once in the repository and then make the changes (setting the third value to `5.88` and in the other case setting the first six observations to `null`) on the fly after the data is `require`d? 

I only have one other, very minor nit-picky comment: In the first equation, `m` should be `m_2`.

**Comment by kgryte** [comment]
Re: eqn. Noted.

Re: on-the-fly. If the data was only stored once, to have three independent data sets, it would require deep copying to prevent shared state. Not necessarily opposed to this. As elsewhere, the primary motivation for duplication was to allow isolated `requires`; e.g., when browserifying. 

As it is still early days in finding out how NPM should be used to distribute data, I am not certain regarding the balance between modularity and parsimony.

**Comment by Planeshifter** [comment]
Good point you raised concerning shared state. It would be very confusing if a user loaded all three data sets, changed the values of one and suddenly all the others would have changed, too. While deep-copying is an option, this will slow things down for large data sets, precisely those for which storing duplicate data sets on disk might not be appropriate. Maybe one should think of loading the data sets manually via `fs` instead of going the `require` route? Anyway, :+1:  for publishing this module to npm.

**Comment by kgryte** [comment]
Awesome. Thanks for looking it over.
